### ISSUE TITLE
Missing line plugin.yml

### ISSUE THREAD

**Issue by andris155** [mcmonkey4eva/monkeyslockette#2]
```
21:43:07] [Server thread/ERROR]: Error occurred while enabling monkeysLockette v1 (Is it up to date?)
ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
    at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405) ~[?:?]
    at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
    at monkeysLockette.monkeysLockette.onEnable(monkeysLockette.java:261) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

```

Missing line: softdepend: [Vault, WorldGuard]

**Comment by mcmonkey4eva** [comment]
As noted in the readme, `This plugin was started when I was not so great at Java or Minecraft stuff and bares some historical troubles from that.` This plugin is not really maintained or used much.
Nonetheless I've fixed this, as I've been using this plugin on an ancient server that's for whatever reason still running somehow.
